version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: go-postgres-db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"  # ローカルから接続する場合のみ開く
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile # GoアプリケーションのDockerfile
    container_name: go-app
    restart: always
    env_file: .env
    ports:
      - "8080:8080" # アプリケーションのポート (例)
    depends_on:
      - db

volumes:
  db_data:
