version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: go-postgres-db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"  # ローカルから接続する場合のみ開く
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile # GoアプリケーションのDockerfile
    container_name: go-app
    restart: always
    env_file: .env
    ports:
      - "8080:8080" # アプリケーションのポート (例)
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    depends_on:
      - db
    volumes:
      - ./config/servers.json:/pgadmin4/servers.json


volumes:
  db_data:
